source 'https://rubygems.org'

gem 'rack-lineprof', :git => 'git://github.com/kainosnoema/rack-lineprof.git',
                     :branch => 'master'
gem 'puma'
gem 'sinatra'
gem 'erubi'
gem 'mysql2'
gem 'mysql2-cs-bind'

group :development do
  gem 'sinatra-contrib'
end
